{
  "name": "UB Kontor",
  "version": "1.0",
  "summary": "Web admin kontor",
  "sequence": 10,
  "description": """Own ERP System""",
  "category": "Productivity",
  "website": "",
  "license": "LGPL-3",
  "depends": ['base', 'web', 'hr', 'mail', 'om_account_accountant', 'l10n_mn', 'account'],
  "qweb": [
    'static/src/xml/user_access_type_template.xml',
    'static/src/xml/pay_address_payment_reconciliation_widget.xml',
    'static/src/xml/pay_bank_statement_reconciliation_widget.xml'
  ],
  "data": [
    "security/groups.xml",
    "security/security.xml",
    "security/ir.model.access.csv",
    "views/view.xml",
    "views/ref.xml",
    "views/counter.xml",
    "views/sequence.xml",
    "views/service.xml",
    "views/qpay.xml",
    "wizards/pay_receipt_wizard.xml",
    "wizards/counter_line_xls_reader_wizard.xml",
    "wizards/service_address_creator_wizard.xml",
    "wizards/pay_receipt_change_days_wizard.xml",
    "wizards/pay_reciept_items_search_wizard.xml",
    "wizards/ref_apartment_change_inspector_wizard.xml",
    "wizards/ref_address_change_services_wizard.xml",
    "wizards/bank_statement_json_loader_wizard.xml",
    "wizards/pay_receipt_create_invoice_wizard.xml",
    "wizards/bank_statement_export_json_wizard.xml",
    "wizards/service_payment_xls_reader_wizard.xml",
    "wizards/service_address_change_day.xml",
    "reports/receipt/pay_receipt_pdf_report_wizard.xml",
    "reports/residual/pay_residual_pdf_report_wizard.xml",
    "reports/residual/pay_user_residual_pdf_report_wizard.xml",
    "wizards/pay_payment_register.xml",
    "reports/pay_income_pdf_report_wizard.xml",
    "reports/residual/pay_residual_pdf_report_template.xml",
    "reports/residual/pay_user_residual_pdf_report_template.xml",
    "reports/receipt/pay_receipt_pdf_report_template.xml",
    "reports/pay_income_pdf_report_template.xml",
    "reports/receipt/pay_receipt_detail_pdf_report_template.xml",
    "reports/receipt/pay_receipt_detail_pdf_report_wizard.xml",
    "reports/residual/pay_residual_list_user_balance_report_wizard.xml",
    "reports/residual/pay_customer_residual_balance_pdf_report_wizard.xml",
    "reports/residual/pay_residual_list_user_balance_report_template.xml",
    "reports/residual/pay_customer_residual_balance_pdf_report_template.xml",
    "reports/uoo/pay_uoo_pdf_report_wizard.xml",
    "reports/uoo/pay_uoo_detail_pdf_report_wizard.xml",
    "reports/uoo/pay_uoo_pdf_report_template.xml",
    "reports/uoo/pay_uoo_detail_pdf_report_template.xml",
    "reports/water_heat_management/water_usage_list_pdf_report.xml",
    "reports/water_heat_management/water_usage_list_pdf_report_template.xml",
    "reports/water_heat_management/water_report_pdf_wizard.xml",
    "reports/water_heat_management/water_report_pdf_template.xml",
    "reports/water_heat_management/heat_report_pdf_wizard.xml",
    "reports/water_heat_management/heat_report_pdf_template.xml",
    "reports/residual/pay_three_month_user_residual_list_pdf_report_wizard.xml",
    "reports/residual/pay_three_month_user_residual_list_pdf_report_template.xml",
    "reports/water_heat_management/counter_list_inspector_report.xml",
    "reports/water_heat_management/counter_list_inspector_report_template.xml",
    "wizards/pay_payment_change_account_wizard.xml",
    "wizards/pay_import_invoice_wizard.xml",
    "wizards/ref_address_change_type_wizard.xml",
    "wizards/service_address_xls_reader_wizard.xml",
    "wizards/pay_address_payment_transfer_wizard.xml",
    "wizards/counter_counter_approve_wizard.xml",
    "wizards/pay_bank_statement_reconciliation_wizard.xml",
    "wizards/ref_address_adjustment_xls_reader_wizard.xml",
    "wizards/pay_receipt_address_invoice_search.xml",
    "wizards/central_heating_station_allocation_wizard.xml",
    "views/pay.xml",
    "views/auth.xml",
    "views/menu.xml",
    "views/hr_emlpoyee.xml",
    "views/data.xml",
    "views/account.xml",
    'views/osnaug_pay_receipt_wizard_views.xml',
    'views/osnaug_period_views.xml',
    'views/osnaug_period_wizard_views.xml',
    'views/osnaug_pay_receipt_views.xml',
    'views/osnaug_pay_receipt_wizard_views.xml',
    "reports/write_off_debt_report.xml",
    "reports/invoice_pdf_report.xml",
    "reports/invoice_pdf_report_template.xml",
    "reports/payment_details_pdf_report.xml",
    "reports/payment_details_pdf_report_template.xml",
    "reports/not_pay_apartment_pdf_report_template.xml",
    "reports/not_pay_apartment_pdf_report.xml",
  ],
  "demo": [],
  "installable": True,
  "application": True,
  "auto_install": False,
}
